#!/bin/sh -e
# Buildfile for AirDoodle on Raspberry Pi

# With BNO055
g++ -std=c++11 -pthread Adafruit_BNO055_Pi.cpp AirDoodle.cpp -o AirDoodle -lwiringPi -lbluetooth -lgrt -lm

# With MPU6050
#g++ -std=c++11 -pthread I2Cdev.cpp MPU6050.cpp AirDoodle.cpp -o AirDoodle -lwiringPi -lbluetooth -lgrt -lm