#!/bin/sh -e
# Buildfile for DataCollection on Raspberry Pi

# With BNO055
g++ Adafruit_BNO055_Pi.cpp DataCollection.cpp -o DataCollection -lwiringPi

# With MPU6050
#g++ I2Cdev.cpp MPU6050.cpp DataCollection.cpp -o DataCollection -lwiringPi
