#!/bin/sh -e

# Collect Data
# $1 = gestures, $2 = numSamples, $3 = outputFile (Raw Data)
sudo ./DataCollection $1 $2 $3

# Remove x gyro (bad for classification)
sudo cut -d " " -f 2- $3 > "$3.nogx"

# Parse Data
# $4 = dataset name, $3 = inputFile (output of last stage), $5 = outputFile (Formatted Data)
sudo ./generateFormattedDataFile $4 "$3.nogx" $5

# Train/Classify Data
# $5 = inputFile (output of last stage), $6 = outputFile (Model)
sudo ./dtwPipeline $5 $6
