#!/bin/sh -e

# Args: $1 Output folder

mkdir $1
dN=alpha

# Script: $1 = gestures, $2 = numSamps, $3 = outputFile (Raw)
# 		$4 = numCols
# 		$5 = setName, $6 = outputFile (Formatted),
#		$7 = outputFile (Model)
./StreamlinedDataCollectionScript abcdefghijklmnopqrstuvwxyz 20 "$1/$dN_Raw.txt" 3 Pi_dleLR "$1/$dN_Ordered.txt" "$1/$dN_Model.txt"
